version: '3.1'
services:
  db:
    image: postgres:16
    restart: on-failure
    environment:
      POSTGRES_USER: zammad
      POSTGRES_DB: zammad
      POSTGRES_PASSWORD: zammadpwd
    ports:
      - '5432:5432'
  adminer:
    image: adminer:4
    restart: on-failure
    environment:
      ADMINER_DESIGN: nette
    ports:
      - '8080:8080'
    depends_on:
      - db
  redis:
    image: redis:7
    restart: on-failure
    ports:
      - '6379:6379'
